### ISSUE TITLE
Delay loading of /api/v1/versions

### ISSUE THREAD

**Issue by steveyken** [crossroads/app.goodcity#401]
When an authenticated user loads the app, an API call is made to /api/v1/versions. For users who have a few offers, this call can take a very long time to load. (e.g. I have 14 offers and /api/v1/versions was taking 30+ seconds.

On admin.goodcity.hk, we load versions with filtering when the specific messages page is opened `/api/v1/versions?for_offer=true&item_id=12345` this typically returns in <100ms.

We would like to replicate this behaviour on the donor app to improve load speeds. It should only affect the messages screens for offer and items.

**Comment by steveyken** [comment]
@patrixr did we ever implement this feature?

**Comment by patrixr** [comment]
@steveyken I believe we did

**Comment by steveyken** [comment]
Confirmed versions are not loading anymore 💯
