### ISSUE TITLE
New feature: user can edit and delete their account

### ISSUE THREAD

**Issue by steveyken** [crossroads/app.goodcity#406]
Add a new feature to enable the user to edit details in their account and also delete it.

![image](https://user-images.githubusercontent.com/149198/191922590-07993f48-27d3-49d1-a213-4eb84b94d6fc.png)

![my-account-view](https://user-images.githubusercontent.com/149198/191945042-f371644a-7aec-48e8-930e-a9ab693e9b9f.jpeg)

![my-account-edit](https://user-images.githubusercontent.com/149198/191945070-f257e581-fe42-41cc-a7e8-46fed547faee.jpeg)

You could consider a view and edit screen or just edit screen if that works better.

Notice the 'Delete account' link, which would lead to a screen with the text below:

--------------------------------

DELETE ACCOUNT SCREEN

You may request to delete your account at any time.

If you choose to delete your account:
* we will delete your personal information
* we will be unable to contact you further about your donations
* your content such as photos and messages will be deleted
* if you have made an offer, we will need to retain some non-personal information about the items for our offical donation records

(if any offers.state NOT IN ('closed', 'cancelled'))

[DELETE ACCOUNT greyed out]

NOTE: You still have an offer that is in progress. As we still need to be in contact with you, we cannot delete your account until your offer has been either completed or cancelled. Please message us direct and we will process your request.

(else)

[DELETE ACCOUNT red button]

(end if)

Note: pressing the red button should initiate a modal pop-up "Are you sure you want to delete your account? It cannot be recovered."

--------------------------------

DELETE ACCOUNT SUCCESS SCREEN

Your account has been scheduled for deletion and will be removed shortly.

Thank you for using GoodCity.HK

We hope to see you again!

**Comment by steveyken** [comment]
The delete button should send a PUT request to '/api/v1/users/1232/delete

**Comment by steveyken** [comment]
@patrixr I think this is ready to be worked on whenever you are able. Many thanks!

**Comment by patrixr** [comment]
@steveyken PR in progress here: https://github.com/crossroads/app.goodcity/pull/407

Endpoint seems to be missing from staging/master tho

**Comment by steveyken** [comment]
I'm in the process of adding two new endpoints:

can_delete specifies whether it is possible for the user account to be deleted right now. This can drive the state of the greyed out DELETE button as it includes more specific logic and cases for checking valid user deletion.

```
GET /api/v1/users/1/can_delete
returns
200 {"can_delete":false}
OR 200 returns {"can_delete":true}
```

The main endpoint is the following, which will check 'can_delete' again and schedule a task to delete the user. This will always return status 200.
```
DELETE /api/v1/users/1
returns 200 "User scheduled for deletion"
```

**Comment by steveyken** [comment]
@patrixr the `users/1/can_delete` and `users/1/delete` endpoints are now on staging

**Comment by steveyken** [comment]
I've simplified the endpoints and removed the `can_delete` url now.

The DELETE endpoint is now on staging:

```
DELETE /api/v1/users/1
# returns one of the following
422 {"result":false, "reason": "User has active offers"}
422 {"result":false, "reason": "User has orders"}
422 {"result":false, "reason": "User has roles"}
200 {"result":true, "reason": "User scheduled for deletion"}
```
