### ISSUE TITLE
Improve donor splash screen on apps

### ISSUE THREAD

**Issue by steveyken** [crossroads/app.goodcity#413]
The cordova splash screen logo is too tiny and looks terrible. This needs adjusting to a better size.

**Comment by omsurase** [comment]
I would like to work on this

**Comment by steveyken** [comment]
Thank you. I have an image I will upload shortly to this issue.

**Comment by Harsh3363** [comment]
Hi @steveyken if this issue is still not solved can you please assign this to me

**Comment by steveyken** [comment]
My apologies, this is an old ticket and has already been fixed
